# Generated by Django 5.0.9 on 2024-10-27 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_user_appointment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user_id',
            new_name='appointment_user_id',
        ),
    ]
