# Generated by Django 5.0.9 on 2024-10-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_user_id_appointment_appointment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_user_id',
            new_name='user_id',
        ),
    ]
